### ISSUE TITLE
criware sn.bin decoding problem

### ISSUE THREAD

**Issue by Todaymayfly** [YuriSizuku/GalgameReverse#8]
hi!

I used your "criware" codes, and in case of "xtx_font.py" it works really well.

But for "iwaihime_pc_decrypt.c" when I run this code, it failed to complete execution(like be stuck in an infinite loop).

Here's how I did.

compile the code(iwaihime_pc_decrypt.c) and execute from command line
"iwaihime_pc_decrypt.exe sn.bin"
(I tested with 4 games - crosschannel final complete edition, root double, iwaihime download edition, iwaihime steam edition)

Am I doing something wrong?

Please understand, I have no knowledge of programming

Can you help me?

**Comment by Todaymayfly** [comment]
I've just solved the problem!

The issue was related to x64 mode. (I didn't check your closed issues lol)

![outbin](https://github.com/YuriSizuku/GalgameReverse/assets/141988143/8bfb6cba-6677-48bc-bc11-e6db96b6696d)

It doesn't look that clean, but it worked anyway.

I think I can build tools to edit texts, but could you give me some tips or utils to edit this decoded file?

I mean, this is single large file, doesn't seemed that easy(to edit texts).

And,

Could you please provide a more detailed explanation of how to 'encrypt'?

I have no knowledge about lzss. :'(

Thank you

**Comment by YuriSizuku** [comment]
Thank you for your questions. 

Because this game is binary script, in which the text is between opcodes. 
I have write a tool to export text and import text if no longer the original text.  See [bintext](https://github.com/YuriSizuku/ReverseUtil/blob/master/script/bintext.py). 

As for the lzss compress (called encrypt is because that I didn't notice it is lzss at first), you can try to use [lzss](https://github.com/YuriSizuku/ReverseThirdparty/blob/master/include/lzss.h).

**Comment by Todaymayfly** [comment]
Thank you so much!

really appreciate your work
